import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
import path from 'path';
const here = path.dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('pageerror', e => console.log('EXC:', e.message));
await page.addInitScript(() => { for (const k of ["text","handschrift","bild"]) localStorage.setItem("tour_"+k, "1"); });
await page.goto('file://' + path.join(here, '..', 'index.html'));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/lac_test/brand_light.png' });
await page.click('#btnTheme');
await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/lac_test/brand_dark.png' });
await page.goto('file://' + path.join(here, '..', 'app', 'handschrift.html'));
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/lac_test/brand_app.png', clip: { x: 0, y: 0, width: 700, height: 500 } });
console.log('Titel:', await page.title());
await browser.close();
