import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
import path from 'path';
const here = path.dirname(fileURLToPath(import.meta.url));
const root = 'file://' + path.join(here, '..');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('pageerror', e => console.log('EXC:', e.message));
await page.addInitScript(() => { for (const k of ["text","handschrift","bild"]) localStorage.setItem("tour_"+k, "1"); });
await page.goto(root + '/index.html');
await page.waitForTimeout(2800);  // Wortmarken-Animation abwarten
await page.screenshot({ path: '/tmp/lac_test/polish_landing.png' });
await page.goto(root + '/app/index.html');
await page.fill('#inpText', 'Feinschliff');
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/lac_test/polish_text_light.png', clip: { x: 0, y: 0, width: 750, height: 950 } });
await page.click('#btnTheme');
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/lac_test/polish_text_dark.png', clip: { x: 0, y: 0, width: 750, height: 950 } });
await browser.close();
