import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
import path from 'path';
const here = path.dirname(fileURLToPath(import.meta.url));
const appDir = 'file://' + path.join(here, '..', 'app');
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('pageerror', e => console.log('EXC:', e.message));
await page.goto(appDir + '/handschrift.html');
await page.evaluate(() => localStorage.clear());
await page.setInputFiles('#fileImport', '/Users/tomhenniger/Downloads/toms_handschrift.handschrift.json');
await page.waitForTimeout(300);
await page.goto(appDir + '/bild.html');
await page.setInputFiles('#fileImg', '/tmp/lac_test/testbild.png');
await page.waitForTimeout(600);
await page.selectOption('#inpStyle', 'ascii');
const fonts = await page.evaluate(() => [...document.getElementById('inpAsciiFont').options].map(o => o.value));
console.log('Handschrift verfügbar:', fonts.find(f => f.startsWith('hw_')) || 'NEIN');
await page.selectOption('#inpAsciiFont', 'hw_toms_handschrift');
await page.fill('#inpACell', '4');
await page.dispatchEvent('#inpACell', 'input');
await page.waitForTimeout(1500);
console.log(await page.evaluate(() => document.getElementById('stInfo').textContent));
await page.screenshot({ path: '/tmp/lac_test/stil_ascii_hw.png', clip: { x: 340, y: 0, width: 1160, height: 880 } });
await browser.close();
